MOVE_UP = 1;
MOVE_LEFT = 2;
MOVE_RIGHT = 3;
MOVE_DOWN = 4;
SONG = 5;
FULL = 6;
PASSIVE = 7;
STOP = 8;

Debug = True

# real data
CAMERA_ADDR = "/irobot/cv/raw_data"
DRIVER_ADDR = "/irobot/key"

# cv
CV_CONE_ADDR = "/irobot/cv/cone"
CV_FACE_ADDR = "/irobot/cv/face"

# speech recognition
SPEECH_COMMAND_ADDR = "/irobot/speech_command"



# speech type
COMMAND_COME_HERE = 3
COMMAND_COME_HERE_TEXT = ["come here"]

COMMAND_STOP = 1

COMMAND_STOP_TEXT = ["stop"]

COMMAND_DELIVER = 2
COMMAND_DELIVER_TEXT = ["deliver"]

Commands = [[COMMAND_COME_HERE,COMMAND_COME_HERE_TEXT],
            [COMMAND_STOP,COMMAND_STOP_TEXT],
            [COMMAND_DELIVER, COMMAND_DELIVER_TEXT]]

# STATE
STATE_DELIVER = 0
STATE_COME = 1
STATE_LISTEN = 2
STATE_WAIT_CMD = 3





# THRESHOLD
STRAIGHT_THRESHOLD_X = 0.6
STOP_THRESHOLD_HEIGHT_CONE = 0.5
STOP_THRESHOLD_HEIGHT_FACE = 0.35
# STOP_THRESHOLD_Y_FACE = 0.5


ITEM_NOT_FOUND = -10
