// Generated by gencpp from file CSE_291_team5_project/CVMessage.msg
// DO NOT EDIT!


#ifndef CSE_291_TEAM5_PROJECT_MESSAGE_CVMESSAGE_H
#define CSE_291_TEAM5_PROJECT_MESSAGE_CVMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace CSE_291_team5_project
{
template <class ContainerAllocator>
struct CVMessage_
{
  typedef CVMessage_<ContainerAllocator> Type;

  CVMessage_()
    : header()
    , width(0.0)
    , height(0.0)
    , x(0.0)
    , y(0.0)  {
    }
  CVMessage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , width(0.0)
    , height(0.0)
    , x(0.0)
    , y(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::CSE_291_team5_project::CVMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::CSE_291_team5_project::CVMessage_<ContainerAllocator> const> ConstPtr;

}; // struct CVMessage_

typedef ::CSE_291_team5_project::CVMessage_<std::allocator<void> > CVMessage;

typedef boost::shared_ptr< ::CSE_291_team5_project::CVMessage > CVMessagePtr;
typedef boost::shared_ptr< ::CSE_291_team5_project::CVMessage const> CVMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::CSE_291_team5_project::CVMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::CSE_291_team5_project::CVMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace CSE_291_team5_project

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'CSE_291_team5_project': ['/home/sayen/Documents/work/assignments/CSE_291_team5_project/src/CSE_291_team5_project/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::CSE_291_team5_project::CVMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::CSE_291_team5_project::CVMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::CSE_291_team5_project::CVMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::CSE_291_team5_project::CVMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::CSE_291_team5_project::CVMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::CSE_291_team5_project::CVMessage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::CSE_291_team5_project::CVMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6d9aa4dd16dec75d285edda4b2da7c7";
  }

  static const char* value(const ::CSE_291_team5_project::CVMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6d9aa4dd16dec75ULL;
  static const uint64_t static_value2 = 0xd285edda4b2da7c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::CSE_291_team5_project::CVMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "CSE_291_team5_project/CVMessage";
  }

  static const char* value(const ::CSE_291_team5_project::CVMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::CSE_291_team5_project::CVMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 width\n\
float32 height\n\
float32 x\n\
float32 y\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::CSE_291_team5_project::CVMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::CSE_291_team5_project::CVMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CVMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::CSE_291_team5_project::CVMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::CSE_291_team5_project::CVMessage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CSE_291_TEAM5_PROJECT_MESSAGE_CVMESSAGE_H
